### PR TITLE
Scikit-style learner 

### PR DESCRIPTION
**Pull request by apoorvalal**
Addressing my own issue https://github.com/JamesYang007/adelie/issues/114
Added a very basic `GroupElasticNet` class that provides a `fit, predict, score` methods that lets one use adelie solvers as drop-in replacements for other regression learners.

[Minimal working example in docs](https://github.com/apoorvalal/adelie/blob/skapi/docs/sphinx/user_guide/notebooks/sklearn_api.ipynb)

### CODE REVIEW

**Comment by apoorvalal** [comment]
you could even call the estimation class `Glmnet` for old times' sake (ask Trevor/Rob for permission :smile: )

**Comment by JamesYang007** [comment]
Thanks so much for doing this! I skimmed it a bit and it looks great!! I'll go through it more carefully on Thursday.

**Comment by apoorvalal** [comment]
Happy to help; excited to use it. Figured adding a cleaned-up version of my testing notebook would help get people started.

**Comment by apoorvalal** [comment]
bump

**Comment by JamesYang007** [comment]
Thanks for the bump - I promise I'm not ignoring it! I've been sidetracked with a separate project. I'm nearing my graduation date, so things are getting a bit hectic 🥲. I'll merge things this weekend along with the rest of my other updates.

**Comment by apoorvalal** [comment]
oof, no pressure; been there. good luck!

**Comment by apoorvalal** [comment]
oh also QQ for you since you make heavy use of compiled code in this library: any idea how to create pypi-compatible portable python wheels with github actions? I have [this](https://github.com/apoorvalal/pyensmallen) small library to run optimization w ensmallen and haven't been able to get it built in an acceptable form.

**Comment by JamesYang007** [comment]
Ah yes, I was also stuck on this at some point. Turns out, there's a great tool called `cibuildwheels`. I found about it by inspecting `numpy` and `scikit-learn` GitHub action workflows. I adapted my wheel-building script from theirs. Here's the section in my [workflow](https://github.com/JamesYang007/adelie/blob/094144eb221dc3c0cd5ef8efe0ea8768296b23df/.github/workflows/wheels.yml#L40-L53) that uses it. Hope this helps!

**Pull request merged**
